
spring:
  datasource:
    url: jdbc:mysql://192.168.221.129:3306/hospital?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Yjj20030120


mybatis-plus:
  configuration:
    #开启日志功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl