spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.221.129:3306/hospital?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Yjj20030120
#      password: qazwsxedc
  redis:
    port: 6379
    host: localhost
#    host: 192.168.221.128
#    password: Yjj20030120
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
        max-wait: 100ms
# 123.60.176.144


mybatis-plus:
  configuration:
    #开启日志功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto   #主键自增

#服务器端口配置
server:
  port: 80


logging:
  level:
    com.shu: debug
